image: node:20.2.0

before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

cache:
  paths:
    - .yarn

pages:
  stage: build
  script: yarn build
  artifacts:
    paths:
      - build
  only:
    - main
