<script>
  import { remote } from "$lib/header";
  import SectionHeader from "../SectionHeader.svelte";
</script>

<SectionHeader
  title="Development"
  subtitle="Identify targeted audience’s needs"
/>

<p>
  After we have clarified the problem we want to solve, we need to fully develop
  it. During this stage of development, we wanted to confirm the needs by
  investigating the local area and formed a questionnaire to survey residents’
  drinking habits.
</p>

<p>
  To comprehensively and objectively reflect the current situation of the
  problem, the proportion of males and females is close to 1:1 in this study.
  Regarding that the drinking habits of people inside a single unit of household
  are consistent, we separated our survey subjects into individual and family.
  In this way, we could avoid inaccurate data generated by some repeated
  answers.
</p>

<figure>
  <div class="two">
    <img src={remote("/human-practices/chart-1.png")} alt="chart-1" />
    <img src={remote("/human-practices/chart-2.png")} alt="chart-2" />
  </div>
  <figcaption>Figure X: 213</figcaption>
</figure>

<p>
  The result shows that bulk water and bottled water together account for the
  largest proportion of all sources of drinking water. Both people who drink
  bottled water and people who drink bulk water make up 38.1% of the whole group
  respectively. Nearly half (40%) of the participants often drink bottled water
  and 27.5% of them choose to "drink bottled water every day”. In short,
  drinking water that contains microplastics has occurred frequently in every
  household.
</p>

<figure>
  <div class="two">
    <img
      src={remote("/human-practices/chart-3.png")}
      alt="chart-3"
      style="object-fit: contain;"
    />
    <img src={remote("/human-practices/chart-4.png")} alt="chart-4" />
  </div>
  <figcaption>Figure X: 213</figcaption>
</figure>

<p>
  Problems came along with it. Most of the barreled drinking water we buy has a
  large capacity, causing the habit of storing them to form among households.
  Regardless the time accumulated on the way of delivering bottled water to each
  household, the data shows that most households store their drinking water(in
  plastic containers) for a week or longer, and some even reach a month. There
  is no need to say that, this whole, long process of storage will enable an
  increasing amount of microplastics to remain in drinking water.
</p>

<img
  src={remote("/human-practices/chart-5.png")}
  alt="chart-5"
  style="width:100%"
/>

<p>
  To dive into the topic of microplastics, the data shows that people have
  already formed a preliminary understanding of microplastics 66.3% of
  participants have heard of this issue before. Among them, 47.5% of
  participants believe that plastic bottles have a high likelihood of containing
  microplastics, 56.5% of them mistakenly believe that microplastics come from
  food and water sources, and 28.2% of them focus on the bottle itself.
</p>

<figure>
  <div class="two">
    <img
      src={remote("/human-practices/chart-6.png")}
      alt="chart-6"
      style="object-fit: contain;"
    />
    <img
      src={remote("/human-practices/chart-7.png")}
      alt="chart-7"
      style="object-fit: contain;"
    />
    <img src={remote("/human-practices/chart-8.png")} alt="chart-8" />
  </div>
  <figcaption>Figure X: 213</figcaption>
</figure>

<p>
  The result of this survey clearly showed the necessity of our project. Our
  team believed that this study is reliable and effective enough to reflect that
  the <b
    >residues of microplastic in drinking water have begun to receive more and
    more attention and that under the threat of microplastics, daily drinking
    water is no longer reassuring.</b
  >
</p>
